### PR TITLE
allow dispatch and getState from cmds

### PR DESCRIPTION
**Pull request by bdwain**
initial implementation idea for #67

### CODE REVIEW

**Comment by bdwain** [comment]
usage: 

```js
function log1(dispatch){
  console.log('log1');
  dispatch({type: 'log2'});
}

function log2(getState){
  const foo = getState().bar;
  console.log(foo);
}

function handleSomeAction(state){
  return loop(state, Cmd.call(log1, () => {return {type: 'log 1 done'}}, Cmd.getDispatch));
}
```

**Comment by bdwain** [comment]
i've been using this in prod for a bit now. it works really well. it really simplifies a lot of my effects and lets them become more generic side effect functions.

**Comment by bdwain** [comment]
any thoughts on this @lukewestby ?

**Comment by lukewestby** [comment]
I just finished a big rewrite at https://github.com/redux-loop/redux-loop/pull/95

In the notes there's a section on why I don't want to bring in stuff from the rest of the redux API into the redux-loop APIs

**Pull request closed without merging**
