### PR TITLE
Add documentation to TS definitions

### PR DESCRIPTION
**Pull request by stereobooster**
This is not final version. Just an idea. WDYT?

screen shot 2018-08-02 at 16 38 51

### CODE REVIEW

**Comment by bdwain** [comment]
This is great! Thanks! I can merge this unless there was more you wanted to add.

**Comment by stereobooster** [comment]
I can add the rest of it. I didn't do it because wanted to show it to you first. Another thing came to my mind, how we will make sure it will not get outdated. Maybe we need one source of truth from which we will generate all documentation jsdoc or something

**Comment by bdwain** [comment]
I think for now we can just update the docs, and then worry about keeping it up to date separately. The library is not changing too quickly so I think it's fine to just try to make sure it gets updated with each pr.

Thanks!

**Comment by bdwain** [comment]
Closing due to inactivity. I can reopen if needed.

**Pull request closed without merging**
