### PR TITLE
Add clear cmdsQueue after replace reducer

### PR DESCRIPTION
**Pull request by Fyzu**
After dynamically replace reducer and dispatch any action, old cmds running again.

Example: http://s.csssr.ru/U5E1S7FNC/20180301163042.png
In example, after "LOCATION_CHANGE", i will replace reducer and call dispatch.
Old cmd ''[3] items/ACTION", running again.

### CODE REVIEW

**Comment by bdwain** [comment]
Are you using redux-devtools? That is typically the cause of the cmds re-running after replacing the reducer. It's because redux devtools re-dispatches every action when you replace the reducer. You can avoid that by setting shouldHotReload to false. It's an option that can be used for the chrome extension or for regular redux devtools.

**Comment by Fyzu** [comment]
Yes, i used redux-devtools.
But it ok when re-run only cmd result actions?

**Comment by bdwain** [comment]
it doesn't re-run cmds. redux-devtools creates its own instance of your store. so if you re-dispatch all actions, some of those will trigger cmds, which will cause side effects to get re-run. turning off shouldHotReload would solve the problem, it will

**Comment by Fyzu** [comment]
But, why does this happen only after replaceReducer and call dispatch any action?

**Comment by bdwain** [comment]
because when you call replaceReducer, redux-devtools re-dispatches every action it ever saw. so if you handle action FOO by running a Cmd, when you call replace-reducer, redux-devtools redispatches FOO, which reruns the Cmd. If you turn off shouldHotReload, it will prevent the devtools from redispatching FOO, so the Cmd won't run again.

**Comment by skoestler** [comment]
For what its worth, I tried the suggested solution of setting shouldHotReload to false and it has the unfortunate effect of clearing the the inspector log after replacing the reducer.  Making this change definitely hurts the utility of the dev tools.

**Comment by bdwain** [comment]
yea I've noticed that. I filed an issue a long time ago, but it hasn't been addressed. https://github.com/reduxjs/redux-devtools/issues/378

If the action you want to inspect is getting erased, i recommend adding https://github.com/LogRocket/redux-logger to your app in dev mode

**Pull request closed without merging**
