### PR TITLE
Fix small typos in README links

### PR DESCRIPTION
**Pull request by mDibyo**
Not sure why the last line shows up as a diff. I haven't made any changes to it.

### CODE REVIEW

**Comment by mDibyo** [comment]
After looking at #171, the lowercase is maybe required for gitbook?

**Comment by bdwain** [comment]
It seems to work when i run it locally. what in #171 makes you think lowercase is required?

**Comment by mDibyo** [comment]
I was navigating on Github. The links for liftState etc., weren't working on this page: https://github.com/redux-loop/redux-loop/tree/master/docs/api-docs

But this is probably not the intended way to look at the documentation...

**Comment by mDibyo** [comment]
Ohhh sorry, just realized you were asking about the lowercase. Not sure if its actually required for gitbooks. But thought that might be the case based on this comment: https://github.com/redux-loop/redux-loop/pull/171#issuecomment-361485555

**Comment by bdwain** [comment]
I think what you did is correct. Thanks for catching that. We definitely want it to work on github too.

There are other broken links in addition to the ones you found. Do you mind fixing them too while you're at it? I can also do it if you don't have time.

It's basically just some of the README.md files in the docs folder that have issues.

docs/readme.md: the links you found plus the mergeChildReducers link.
docs/api-docs/readme: liftState, getModel, getCmd, and isLoop

Thanks!

**Comment by mDibyo** [comment]
Sure can do! Will do that later tonight/early tomorrow.

**Comment by mDibyo** [comment]
@bdwain Done!

**Comment by bdwain** [comment]
thank you!

**Pull request merged**
